### ISSUE TITLE
json decode error

### ISSUE THREAD

**Issue by Hairo** [KnightHawk3/Hummingbird#6]
Geting this when trying to get any of the libraries:
```
Traceback (most recent call last):
  File "./animu_rss.py", line 17, in <module>
    bird = hum.get_library("Hairo", status="currently-watching")
  File "/usr/local/lib/python3.4/dist-packages/hummingbird/__init__.py", line 110, in get_library
    for item in r.json():
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 819, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```

**Comment by KnightHawk3** [comment]
This is probably because Hummingbird has changed something and I have not kept up to date for it in a very long time(tm)

Feel free to poke at the library (I like to think its a little bit readable) but otherwise it's mostly unsupported (I will fix it when I get time, that could be a bit) and partially unfinished.

If you want to make your own, look into the API Docs and use Requests to access them.

**Comment by Hairo** [comment]
Weird, is working now, maybe they had some server issues.

**Comment by KnightHawk3** [comment]
Good luck using my library, thanks for using it. Means a lot to me :)
